Description: Stack containing related resources for setting up Athena.
Resources:
  athenavsredshiftgluepolicyA3791110:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:*
              - s3-object-lambda:*
              - lambda:*
              - iam:PassRole
            Condition:
              StringEquals:
                aws:RequestedRegion: eu-central-1
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      Description: ""
      ManagedPolicyName: athena-vs-redshift-glue-policy
      Path: /
    Metadata:
      aws:cdk:path: redshift-vs-athena-stack/athena-vs-redshift-glue-policy/Resource
  athenavsredshiftgluerole872C2FF5:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: athena.amazonaws.com
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: glue.amazonaws.com
        Version: "2012-10-17"
      Description: Role for Athena can connect with theAWS environment including S3
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSGlueServiceRole
        - Ref: athenavsredshiftgluepolicyA3791110
      RoleName: athena-vs-redshift-glue-role
    Metadata:
      aws:cdk:path: redshift-vs-athena-stack/athena-vs-redshift-glue-role/Resource
  athenavsredshiftgluedb:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: "12"
      DatabaseInput:
        Name: athena-vs-redshift-glue-db
    Metadata:
      aws:cdk:path: redshift-vs-athena-stack/athena-vs-redshift-glue-db
  athenavsredshiftqueryresultsFB4E13FA:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: athena-vs-redshift-query-results
      LifecycleConfiguration:
        Rules:
          - AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 3
            ExpirationInDays: 90
            Status: Enabled
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: redshift-vs-athena-stack/athena-vs-redshift-query-results/Resource
  athenavsredshiftgluecrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Role:
        Fn::GetAtt:
          - athenavsredshiftgluerole872C2FF5
          - Arn
      Targets:
        S3Targets:
          - Exclusions:
              - .*input.*
            Path: s3://athena-vs-redshift/output/
      Configuration: '{"Version": 1.0, "Grouping": {"TableGroupingPolicy": "CombineCompatibleSchemas"}}'
      DatabaseName: athena-vs-redshift-glue-db
      Description: Automatically crawls s3://athena-vs-redshift/output/ and adds outputs to a glue table.
      Name: athena-vs-redshift-glue-crawler
      Schedule:
        ScheduleExpression: cron(0 0 * * ? *)
      SchemaChangePolicy:
        DeleteBehavior: DEPRECATE_IN_DATABASE
        UpdateBehavior: UPDATE_IN_DATABASE
      TablePrefix: crawler_
    Metadata:
      aws:cdk:path: redshift-vs-athena-stack/athena-vs-redshift-glue-crawler
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/1WMzQqDMBCEn8V73FqFQq+114LYByhr3NqtMYH8IBLy7tV6aU/zzTcwJZwqKDKcXS77MVfcQbx7lKNY1SMyThBvqHGgvjGK5SLqp/4XrVG02S2TGFQgiGu9oscO3XeqLc6KbBKugngJciS/6Z1SEi05E6zcb364Nrpnz0Yn0Sz+ZfShgmMB5+ztmHMbtOeJoN3zAzbjarrLAAAA
    Metadata:
      aws:cdk:path: redshift-vs-athena-stack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

